/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package View;

import Service.Implement.KhuyenMaiServiceImplement;
import Service.Interface.KhuyenMaiServiceInterface;
import ViewModel.KhuyenMaiViewModel;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author pc
 */
public class LichSuKhuyenMai extends javax.swing.JFrame {

    /**
     * Creates new form LichSuKhuyenMai
     */
    private KhuyenMaiServiceInterface khuyenMaiServiceInterface = new KhuyenMaiServiceImplement();

    public LichSuKhuyenMai() {
        initComponents();
        setDefaultCloseOperation(DISPOSE_ON_CLOSE);
        setLocationRelativeTo(null);
        loadTable();
//         SendMailHD sen = new SendMailHD();
//        sen.setVisible(true);
    }

    public void loadTable() {
        DefaultTableModel dtm = (DefaultTableModel) this.tblKM.getModel();
        dtm.setRowCount(0);
        List<KhuyenMaiViewModel> listKM = khuyenMaiServiceInterface.getAllHetHan();
        for (KhuyenMaiViewModel dv : listKM) {
            dtm.addRow(dv.toDataRow());
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane3 = new javax.swing.JScrollPane();
        tblKM = new javax.swing.JTable();
        btnXoa = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        tblKM.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Mã Khuyến mại", "Tên khuyến mại", "Phần trăm giảm", "Trạng Thái", "Thời gian bắt đầu", "Thời gian kết thúc", "Mô tả"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblKM.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblKMMouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(tblKM);

        btnXoa.setText("Xóa");
        btnXoa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnXoaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 624, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnXoa)
                .addGap(56, 56, 56))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnXoa)
                .addContainerGap(103, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tblKMMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblKMMouseClicked
        int row = this.tblKM.getSelectedRow();
        if (row == -1) {
            return;
        }
        String ma = this.tblKM.getValueAt(row, 0).toString();
        String ten = this.tblKM.getValueAt(row, 1).toString();
        String tien = this.tblKM.getValueAt(row, 2).toString();

        String tt = this.tblKM.getValueAt(row, 3).toString();
        String tgdb = this.tblKM.getValueAt(row, 4).toString();
        String tgkt = this.tblKM.getValueAt(row, 5).toString();
        String mota = this.tblKM.getValueAt(row, 6).toString();
//        this.jlbmkm.setText(ma);
//        this.txtTenKhuyenMai.setText(ten);
//        this.txtTienGiam.setText(tien);
//        // this.cbbTrangThai.setSelectedItem(tt);
//        this.txtThoiGianBatDau.setText(tgdb);
//        this.txtTHoiGianKetThuc.setText(tgkt);
//        this.txtMoTa.setText(mota);

    }//GEN-LAST:event_tblKMMouseClicked

    private void btnXoaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnXoaActionPerformed
        int row = this.tblKM.getSelectedRow();
        if (row == -1) {
            JOptionPane.showMessageDialog(this, "Bạn phải chọn 1 dòng để xóa");
            return;
        }
        Integer ma = Integer.parseInt(this.tblKM.getValueAt(row, 0).toString());
        int confirm = JOptionPane.showConfirmDialog(this, "Xác nhận xóa");
        if (confirm == JOptionPane.YES_NO_OPTION) {
            khuyenMaiServiceInterface.delete(ma);
            JOptionPane.showMessageDialog(this, "Xóa thành công");
            loadTable(); 
        }
    }//GEN-LAST:event_btnXoaActionPerformed

    /**
     * @param args the command line arguments
     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(LichSuKhuyenMai.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(LichSuKhuyenMai.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(LichSuKhuyenMai.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(LichSuKhuyenMai.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new LichSuKhuyenMai().setVisible(true);
//            }
//        });
//    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnXoa;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTable tblKM;
    // End of variables declaration//GEN-END:variables
}
